### ISSUE TITLE
AP / hostapd Support

### ISSUE THREAD

**Issue by multiple1** [FomalhautWeisszwerg/rtl8822bu#11]
Hello,
what are the constraints of the not supported AP Mode?
Is there a possibility to support it?
After some searching there is a RTL8812AU driver for AP mode, but not for the RTL8812BU .

Thanks

**Comment by FomalhautWeisszwerg** [comment]
Because the upstream https://github.com/brandon-bailey/rtl8822bu not supported AP mode.
