### ISSUE TITLE
Need to add support for specific Realtek card

### ISSUE THREAD

**Issue by neils-s** [FomalhautWeisszwerg/rtl8822bu#8]
I used this driver to add support for a Realtek spec USB wireless card.  When I run lsusb, it shows this:
            ID 0bda:b812 Realtek Semiconductor Corp. 
Some google-foo revealed that this card uses the 8820BU chipset, which your driver supports in the 4.13.x Linux kernel.
Unfortunately, this specific USB ID is not supported by the driver.  To get the driver to support this USB device I had to add support for the specific card to the usb_intf.c file.
In particular, I had to change a section of
`./rtl8822bu/os_dep/linux/usb_intf.c`
from this:
`#ifdef CONFIG_RTL8822B`
`	/*=== Realtek demoboard ===*/`
`	{USB_DEVICE(0x0B05, 0x1812), .driver_info = RTL8812}, /* ASUS - Edimax */`
`	{USB_DEVICE(0x7392, 0xB822), .driver_info = RTL8822B}, /* Edimax - EW-7822ULC */`
`	{USB_DEVICE_AND_INTERFACE_INFO(USB_VENDER_ID_REALTEK, 0xB82C, 0xff, 0xff, 0xff), .driver_info = RTL8822B}, /* Default ID */`
`#endif /* CONFIG_RTL8822B */`

to this:
`#ifdef CONFIG_RTL8822B`
`	/*=== Realtek demoboard ===*/`
`	{USB_DEVICE(0x0B05, 0x1812), .driver_info = RTL8812}, /* ASUS - Edimax */`
`	{USB_DEVICE(0x7392, 0xB822), .driver_info = RTL8822B}, /* Edimax - EW-7822ULC */`
`	{USB_DEVICE(0x0BDA, 0xB812), .driver_info = RTL8822B}, /* Realtek card I got from amazon */`
`	{USB_DEVICE_AND_INTERFACE_INFO(USB_VENDER_ID_REALTEK, 0xB82C, 0xff, 0xff, 0xff), .driver_info = RTL8822B}, /* Default ID */`
`#endif /* CONFIG_RTL8822B */`

**Comment by FomalhautWeisszwerg** [comment]
Thanks for your report.
Now, the device 0bda:b812 support on f6390dd072985efb7dae1d4d0bb7922db47a0b82.

Please try it :-)
